# -*- coding: utf-8 -*-
"""Projeto_8-puzzle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qEGTMH0vTP9dOU7dB2SrgUuguhPExMX4
"""

#include <stdio.h>
#include <stdlib.h>  // Para rand() e srand()
#include <time.h>    // Para time()
#include <conio.h>

char ler_movimento();
void imprimir(int puzzle [3][3]);
void altera_puzzle(int puzzle[3][3], char mov, int *linha_vazio, int *col_vazio);
int completo(int puzzle[3][3]);
int main()
{
    int valores[9] = {1, 2, 3, 4, 5, 6, 7, 8, 0}; //0 é o vazio
    int Tabuleiro[3][3];
    int posicao, i, j, POS_lin_VAZIO, POS_col_VAZIO,cont=0,resposta;
    char movimento, movimentos[4]={'W','S','D','A'};

    //CRIANDO O TABULEIRO EMBARALHADO
    srand(time(NULL));

    for(i=0;i<3;i++)
    {
        for(j=0;j<3;j++)
        {
            Tabuleiro[i][j]=valores[cont];
            cont++;
        }
    }
    //VERIFICANDO SE ELE É RESOLVIVEL
    POS_lin_VAZIO=2;
    POS_col_VAZIO=2;
    for(int i=0;i<25;i++)
    {
       //LENDO OS MOVIMENTOS DO JOGADOR
        posicao = rand() % 4;
        movimento=movimentos[posicao];

        //ALTERANDO O PUZZLE
        altera_puzzle(Tabuleiro, movimento, &POS_lin_VAZIO, &POS_col_VAZIO);
    }

    imprimir(Tabuleiro);




    //GUARDANDO A POSIÇÃO DO ZERO
    for(i=0; i<3; i++)
    {
        for(j=0; j<3; j++)
        {
            if(Tabuleiro[i][j] == 0)
            {
                POS_lin_VAZIO = i;
                POS_col_VAZIO = j;
            }
        }
    }

    cont=0;
    while(completo(Tabuleiro))
    {
        //LENDO OS MOVIMENTOS DO JOGADOR
        movimento = ler_movimento();

        //ALTERANDO O PUZZLE
        altera_puzzle(Tabuleiro, movimento, &POS_lin_VAZIO, &POS_col_VAZIO);
        imprimir(Tabuleiro);
        cont++;
        if(cont%20==0)
    {
        if(cont==20)
        {
            printf("\n\nDeseja parar? 1 - sim , 0 - nao: ");
            scanf("%d",&resposta);
            if(resposta==1)
            {
                printf("\n\nVoce nao completou o puzzle, que pena...\nMovimentos = %d\n\n",cont);
                exit(0);
            }
        }
        else if(cont==40)
        {
            printf("\n\nQuer desistir? 1 - sim , 0 - nao: ");
            scanf("%d",&resposta);
            if(resposta==1)
            {
                printf("\n\nFoi quase, mas nao deu, que pena...\nMovimentos = %d\n\n",cont);
                exit(0);
            }
        }
        else if(cont==60)
        {
            printf("\n\nAinda quer mais? 1 - sim , 0 - nao: ");
            scanf("%d",&resposta);
            if(resposta==1)
            {
                printf("\n\nDemorou, mas aceitou seu destino...\nMovimentos = %d\n\n",cont);
                exit(0);
            }
            printf("Quase te peguei nessa eim kkkkk");
        }
        else if(cont==80)
        {
            printf("\n\nAcaba logo com isso, nao tenho o dia todo 1 - sim , 0 - nao: ");
            scanf("%d",&resposta);
            if(resposta==1)
            {
                printf("\n\nMuito obrigado...\nMovimentos = %d\n\n",cont);
                exit(0);
            }
        }
        else if(cont==100)
        {
            printf("\n\nNao era pra ser tao dificil assim, ta tudo bem?\nPular fora? 1 - sim , 0 - nao: ");
            scanf("%d",&resposta);
            if(resposta==1)
            {
                printf("\n\nFoi quase, mas nao deu, que pena...\nMovimentos = %d\n\n",cont);
                exit(0);
            }
        }
        else if(cont==120)
        {
            printf("\n\nGostei da sua resiliencia, vou te acompanhar ate o final\nNao desiste agora 1 - sim , 0 - nao: ");
            scanf("%d",&resposta);
            if(resposta==1)
            {
                printf("\n\nFoi desistir logo agora, que pena...\nMovimentos = %d\n\n",cont);
                exit(0);
            }
        }
        else if(cont==140)
        {
            printf("\n\nNao sei mais como eh o lado de fora...\n Posso dar uma olhadinha? 1 - sim , 0 - nao: ");
            scanf("%d",&resposta);
            if(resposta==1)
            {
                printf("\n\nO que eh tudo isso aqui fora?...\nMovimentos = %d\n\n",cont);
                exit(0);
            }
        }
        else if(cont==160)
        {
            printf("\n\nEu tive tempo de criar uma familia e voce ainda esta aqui\nViver a vida? 1 - sim , 0 - nao: ");
            scanf("%d",&resposta);
            if(resposta==1)
            {
                printf("\n\nPosso aproveita-los e voce pode aproveitar a vida...\nMovimentos = %d\n\n",cont);
                exit(0);
            }
        }
        else if(cont==180)
        {
            printf("\n\nVim me despedir de voce, ja fazem seculos desde que voce começou, ja nao aguento muito mais tempo...");
            printf("\n\nVou deixar meu filho cuidando de voce, 8-puzzle Jr\nQuer acabr com tudo isso? 1 - sim , 0 - nao: ");
            scanf("%d",&resposta);
            if(resposta==1)
            {
                printf("\n\nAdeus, velho amigo, nossos momentos juntos foram incriveis\nMovimentos = %d\n\n",cont);
                exit(0);
            }
        }
        else
        {
            printf("\n\nAgora quer desistir? 1 - sim, 0 - nao: ");
            scanf("%d",&resposta);
            if(resposta==1)
            {
                printf("\n\nFoi muito bom jogar com voce\nMovimentos = %d\n\n",cont);
                exit(0);
            }
        }
    }
    }
    printf("\n\nFoi muito bom jogar com voce\nMovimentos = %d\n\n",cont);
    return 0;
}

int completo(int puzzle[3][3])
    {
        int comp[3][3],pos=0,pos_certa=0,i,j;
        int valores[9]={1, 2, 3, 4, 5, 6, 7, 8, 0};
        for(i=0;i<3;i++)
        {
            for(j=0;j<3;j++)
            {
                if(puzzle[i][j]==valores[pos])
                {
                    pos_certa++;
                }
                pos++;
            }
        }
        if(pos_certa==9)
        {
            return 0;
        }
        return 1;


    }

char ler_movimento()
{
    char mov;

    do
    {
    printf("\n\nDigite o seu movimento (W, A, S, D): ");
    mov = getch();
    printf("%c",mov);

    if(mov!='w' && mov!='W' && mov!='a' && mov!='A' && mov!='s' && mov!='S' && mov!='d' && mov!='D')
    {
        printf("\nMovimento invalido!");
    }
    }while(mov!='w' && mov!='W' && mov!='a' && mov!='A' && mov!='s' && mov!='S' && mov!='d' && mov!='D');

    return mov;
}

void imprimir(int puzzle[3][3])
{

    int i, j;
    system("cls"); // Limpa a tela para exibir o novo estado do tabuleiro
    printf("==================================");
    printf("\nTabuleiro:\n\n");

    for (i = 0; i < 3; i++)
    {
        printf("\t");
        for (j = 0; j < 3; j++)
        {
            // Quando o valor for 0, imprima o caractere de "vazio"
            if (puzzle[i][j] == 0)
            {
                printf("|%c |", 127); // Substitua por 127 (ou outro símbolo como ' ')
            }
            else
            {
                printf("|%d|", puzzle[i][j]); // Caso contrário, imprima o número
            }
        }
        printf("\n");

    }
    printf("\n==================================");
}
void altera_puzzle(int puzzle[3][3], char mov, int *linha_vazio, int *col_vazio)
{
    //GUARDANDO A POSIÇÃO DO VAZIO EM VARIÁVEIS (para não trabalhar com ponteiro)
    int lin = *linha_vazio;
    int col = *col_vazio;
    int novaLinha = lin, novaColuna = col;

    if(mov == 'A' || mov == 'a') // para a esquerda
    {
        novaColuna = col - 1;
    }
    else if(mov == 'W' || mov == 'w') // para cima
    {
        novaLinha = lin - 1;
    }
    else if(mov == 'S' || mov == 's') // para baixo
    {
        novaLinha = lin + 1;
    }
    else if(mov == 'D' || mov == 'd') // para a direita
    {
        novaColuna = col + 1;
    }
    else
    {
        printf("\nMovimento invalido - Use W, A, S, D\n");
        return;
    }

    //VERIFICANDO SE A POSIÇÃO É VÁLIDA (dentro do tabuleiro)
    if(novaLinha < 0 || novaLinha > 2 || novaColuna < 0 || novaColuna > 2)
    {
        printf("\nMovimento invalido - Fora do Tabuleiro\n");
        return;
    }

    //TROCANDO POSIÇÕES
    puzzle[lin][col] = puzzle[novaLinha][novaColuna];
    puzzle[novaLinha][novaColuna] = 0;

    //ATUALIZANDO A POSIÇÃO DO VAZIO
    *linha_vazio = novaLinha;
    *col_vazio = novaColuna;

}